version: '3.9'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped
