name: deploy Crafters Front
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3

      - name: Install dependencies and build application
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          server_port: ${{ secrets.SERVER_PORT }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/"
          target: "/var/www/crafters_front"